[supervisord]
nodaemon=true

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true

[program:laravel-init]
command=/bin/sh -c "
php artisan storage:link || true &&
php artisan config:clear &&
php artisan config:cache
"
priority=10
autorestart=false
