[supervisord]
nodaemon=true

[program:laravel-init]
directory=/var/www
command=/bin/sh -c "php artisan storage:link || true && php artisan optimize:clear && php artisan migrate --path=database/migrations/2026_05_20_124516_add_location_to_build_process_items.php --force"
autostart=true
autorestart=false
priority=1
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:php-fpm]
command=php-fpm -F
autostart=true
autorestart=true
priority=5
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr